title: SweetDate
description: Headless Calendar with native implementations for developer satisfaction
theme: just-the-docs

url: https://sweetdate-calendar.github.io/sd_docs

aux_links:
  Github Repository: https://github.com/SweetDate-Calendar/
