title: SweetDate
description: Headless Calendar with native implementations for developer satisfaction
theme: just-the-docs

url: https://github.com/SweetDate-Calendar

aux_links:
  Github Repository: https://sweetdate-calendar.github.io/sd_docs/
