title: clp-calendar
description: Headless Calendar with native implementations for developer satisfaction
theme: just-the-docs

url: https://maxgronlund.github.io/clp-calendar

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
